/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const Blog = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'published' : IDL.Bool,
  'timestamp' : Time,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addAllowedAdminEmail' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createBlog' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
  'deleteBlog' : IDL.Func([IDL.Nat], [], []),
  'editBlog' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [], []),
  'getAllBlogs' : IDL.Func([], [IDL.Vec(Blog)], ['query']),
  'getAllowedAdminEmails' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getBlog' : IDL.Func([IDL.Nat], [IDL.Opt(Blog)], ['query']),
  'getCallerEmail' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getUserEmail' : IDL.Func([IDL.Principal], [IDL.Opt(IDL.Text)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isSiteLive' : IDL.Func([], [IDL.Bool], ['query']),
  'performAllowListAdminBootstrap' : IDL.Func([IDL.Text], [], []),
  'performDefaultAdminBootstrap' : IDL.Func([IDL.Text], [], []),
  'removeAllowedAdminEmail' : IDL.Func([IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setEmail' : IDL.Func([IDL.Text], [], []),
  'setPublishedStatus' : IDL.Func([IDL.Nat, IDL.Bool], [], []),
  'setSiteLive' : IDL.Func([IDL.Bool], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const Blog = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'published' : IDL.Bool,
    'timestamp' : Time,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addAllowedAdminEmail' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createBlog' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
    'deleteBlog' : IDL.Func([IDL.Nat], [], []),
    'editBlog' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [], []),
    'getAllBlogs' : IDL.Func([], [IDL.Vec(Blog)], ['query']),
    'getAllowedAdminEmails' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getBlog' : IDL.Func([IDL.Nat], [IDL.Opt(Blog)], ['query']),
    'getCallerEmail' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getUserEmail' : IDL.Func([IDL.Principal], [IDL.Opt(IDL.Text)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isSiteLive' : IDL.Func([], [IDL.Bool], ['query']),
    'performAllowListAdminBootstrap' : IDL.Func([IDL.Text], [], []),
    'performDefaultAdminBootstrap' : IDL.Func([IDL.Text], [], []),
    'removeAllowedAdminEmail' : IDL.Func([IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setEmail' : IDL.Func([IDL.Text], [], []),
    'setPublishedStatus' : IDL.Func([IDL.Nat, IDL.Bool], [], []),
    'setSiteLive' : IDL.Func([IDL.Bool], [], []),
  });
};

export const init = ({ IDL }) => { return []; };